script: |
  cd /var/www/html
  git pull origin main

  sudo docker stop $(sudo docker ps -q) || true
  sudo docker rm $(sudo docker ps -aq) || true

  sudo docker build -t restaurant-app .
  sudo docker run -d -p 80:80 restaurant-app